# Generated by Django 3.2.9 on 2021-11-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
