# Generated by Django 3.2.9 on 2021-12-08 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_resolution_product_max_resolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='NativeInOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('native_inout', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='max_resolution',
            field=models.CharField(blank=True, choices=[('4K', '4K60'), ('HD', 'Full HD')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='native_in_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.nativeinout'),
        ),
    ]
