# Generated by Django 3.2.9 on 2021-12-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_nativeinout_native_inout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='native_in_out',
        ),
        migrations.AddField(
            model_name='product',
            name='native_in_out',
            field=models.ManyToManyField(blank=True, null=True, to='products.NativeInOut'),
        ),
    ]
