# Generated by Django 3.2.9 on 2021-12-09 00:20

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_native_in_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='speed',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1Gbe', '1G'), ('10Gbe', '10G')], max_length=10, null=True),
        ),
    ]
