# Generated by Django 3.2.9 on 2021-12-30 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpoint',
            name='test_var',
        ),
    ]
