# Generated by Django 3.2.9 on 2021-12-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBasedAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_based_access', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.SlugField(max_length=20)),
                ('description', models.TextField(blank=True, default='Describe this Product here', max_length=1000, null=True)),
                ('summary', models.TextField(default='short summary', max_length=100)),
                ('protocol', models.CharField(choices=[('IP', 'over IP'), ('Proprietary', 'Proprietary/Non-IP')], max_length=15)),
                ('topology', models.CharField(choices=[('Distributed', 'Distributed'), ('Chassis', 'Central Chassis')], max_length=15)),
                ('videowall_support', models.BooleanField(default=False)),
                ('hdcp_support', models.BooleanField(default=False)),
                ('independent_audio_usb_serial_routing', models.BooleanField(default=False)),
                ('controller_redundancy', models.BooleanField(default=True)),
                ('snmp_support', models.BooleanField(default=False)),
                ('syslog_support', models.BooleanField(default=False)),
                ('user_based_access', models.ManyToManyField(to='solutions.UserBasedAccess')),
            ],
        ),
    ]
