# Generated by Django 3.2.9 on 2021-12-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='description',
            field=models.TextField(blank=True, default='This Description will appear on the Solution`s page', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='summary',
            field=models.TextField(default='This summary will appear in the Compare page', max_length=100),
        ),
        migrations.AlterField(
            model_name='solution',
            name='user_based_access',
            field=models.ManyToManyField(blank=True, to='solutions.UserBasedAccess'),
        ),
        migrations.AlterField(
            model_name='userbasedaccess',
            name='user_based_access',
            field=models.CharField(max_length=30),
        ),
    ]
